export const DEFAULT_SITEURL = "http://localhost:3000";
export const DEFAULT_APIURL = "http://localhost:4000/api/";
export const DEFAULT_TITLE = "TITLE";
export const DEFAULT_DESCRIPTION = "DESCRIPTION";
export const DEFAULT_TWITTER = "@react";
export const DEFAULT_SEP = " | ";
export const DEFAULT_LOGO = "/logo192.png";
export const DEFAULT_FAVICON = "/favicon.ico";
export const DEFAULT_IMAGE = "/logo512.png";
